DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.90
MODEL:
    TYPE: swin_det
    NAME: swin_tiny_patch4_window7
    DROP_PATH: 0.5
    TRANS:
        EMBED_DIM: 96
        STAGE_DEPTHS: [2, 2, 6, 2]
        NUM_HEADS: [3, 6, 12, 24]
        WINDOW_SIZE: 7

